# =============================================================================
# 04_ISG_response.R
# Interferon-stimulated gene (ISG) response scoring per cell type
# in HEV-infected versus mock-treated human intestinal organoids.
#
# The ISG gene set is derived from Schoggins et al. (reference 34 in the
# manuscript) and provided as a CSV file in the data/ directory.
# Scores are computed with Seurat's AddModuleScore() using the SCT assay,
# then compared between mock and HEV conditions per cell type using a
# Wilcoxon rank-sum test with Bonferroni correction (via plot_signature_score).
#
# A separate annotated Seurat object that includes mock-treated cells is
# required for this analysis (hev_mock_norm), as the main integrated object
# (hev) contains only HEV-exposed libraries.
#
# Input:  data/hev_mock_norm_annotated.rds  — annotated Seurat object
#                                             (Mock + HEV-norm; processed
#                                             identically to 01–02)
#         data/isg_Schoggins.csv            — ISG gene list
# Output: outputs/boxplot_sig_schoggins.pdf — Fig. 3E / Suppl. Fig. S12
# =============================================================================

source("R/utils.R")
library(Seurat)
library(tidyverse)

out_dir <- "outputs/"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

# -----------------------------------------------------------------------------
# Step 1: Load the mock + HEV-norm annotated object
# This object was generated by running 01_quality_control.R and
# 02_annotation.R on the mock and HEV-norm libraries jointly and is
# provided as a pre-processed .rds file in the data/ directory.
# -----------------------------------------------------------------------------

seurat_obj <- readRDS("data/hev_mock_norm_annotated.rds")

# Assign treatment labels from library identity
seurat_obj$treatments <- case_when(
  seurat_obj$orig.ident == "hev"     ~ "hev",
  seurat_obj$orig.ident == "IO_mock" ~ "mock",
  TRUE                               ~ NA_character_
)

# -----------------------------------------------------------------------------
# Step 2: Compute ISG module score (Schoggins et al.)
# AddModuleScore() calculates the mean expression of the signature genes
# relative to a set of control genes matched for expression level,
# providing a per-cell score corrected for transcriptional activity.
# -----------------------------------------------------------------------------

sig_schoggins <- read.csv("data/isg_Schoggins.csv", stringsAsFactors = FALSE) %>%
  pull(gene)

seurat_obj <- AddModuleScore(
  object   = seurat_obj,
  features = list(sig_schoggins),
  ctrl     = 5,
  assay    = "SCT",
  slot     = "data",
  name     = "sig_schoggins"
)

# AddModuleScore appends a numeric suffix; strip it for cleaner column naming
score_cols <- grep("^sig_", colnames(seurat_obj@meta.data), value = TRUE)
colnames(seurat_obj@meta.data)[match(score_cols, colnames(seurat_obj@meta.data))] <-
  sub("[0-9]+$", "", score_cols)

# -----------------------------------------------------------------------------
# Step 3: Visualise and test ISG scores per cell type
# plot_signature_score() (defined in utils.R) produces a grouped boxplot
# with Wilcoxon p-values relative to mock for each cell type.
# -----------------------------------------------------------------------------

plot_signature_score(
  seurat_obj      = seurat_obj,
  score_colname   = "sig_schoggins",
  score_label     = "Schoggins ISG signature score",
  celltype_colname= "SingleR_label",
  out_dir         = out_dir
)
